Repository wakatime/semver-action, pull requests merged in 2021-05, with the labels that each got.

#9 Update branch patterns
  README.md
  cmd/generate/generate.go
  cmd/generate/generate_internal_test.go
  cmd/generate/generate_test.go
Labels: enhancement

#11 Fix ancestor tag matching
  cmd/generate/generate.go
  cmd/generate/generate_test.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: bug

#12 Fix git commands
  cmd/generate/generate.go
  cmd/generate/generate_test.go
  cmd/generate/params.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: bug

#14 Add coverage report
  .github/workflows/on_push.yml
  .gitignore
  Makefile
  README.md
Labels: enhancement

#13 Add new conditional for resync prefix
  README.md
  cmd/generate/generate.go
  cmd/generate/generate_internal_test.go
  cmd/generate/generate_test.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: enhancement

#15 Use correct pre-release version for doc and misc branches
  cmd/generate/generate.go
  cmd/generate/generate_test.go
Labels: bug

#16 Improve README
  README.md
  cmd/generate/generate_test.go
Labels: documentation, enhancement
